### ISSUE TITLE
i get this error - No module named 'investorzilla'

### ISSUE THREAD

**Issue by johnfelipe** [avibrazil/investorzilla#5]
ModuleNotFoundError: No module named 'investorzilla'
	Traceback:
	File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	File "/root/investorzilla/investorzilla/streamlit_ui.py", line 11, in <module>
		import investorzilla

this is all my steps in ubuntu 20 

	apt update
	apt upgrade
	shutdown -r now
	sudo su
	cd
	apt install python3-pip
	pip install streamlit
	pip install streamlit --upgrade
	pip install Jinja2==3
	git clone https://github.com/avibrazil/investorzilla
	cd investorzilla/
	pip3 install -r requirements.txt --user
	pip3 install pandas pyyaml sqlalchemy pandas_datareader
	pip3 install streamlit google-api-python-client
	https://docs.google.com/spreadsheets/d/1AE0F_mzXTJJuuuQwPnSzBejRrmui01CfUUY1qyvnbkk

	cd investorzilla/
	streamlit run streamlit_ui.py

pls tell me how solve?

**Comment by avibrazil** [comment]
Install with pip:

pip install investorzilla

Then, create a folder to put your investorzilla.yaml that you’ll have to create by yourself.

Then simply run “investorzilla” into that folder.

Check and tell me the result.

**Comment by avibrazil** [comment]
I need to update the readme. Installation process is much easier now.

**Comment by avibrazil** [comment]
You don´t need to run the `streamlit` command.
Just run `investorzilla` command from the same folder where your `investorzilla.yaml` file lives.

**Comment by avibrazil** [comment]
The Google Sheets backend is good but obsolete because it demands you authenticate with Google everytime in a browser UI. This is what is failling.

Just to get you going, copy the example spreadsheet to your Google Drive and export as CSVs the ledger and balance sheets. Then adapt [this example](https://github.com/avibrazil/investorzilla/blob/main/config_examples/investorzilla.yaml) to your URLs.

I´m updating the README to explain this.

**Comment by johnfelipe** [comment]
https://docs.google.com/spreadsheets/d/1U2SAvRuwcA74heo2dAeFvKuH5zFLowlCGdn4-tcVC9U/edit?usp=sharing

    - type: !!python/name:investorzilla.portfolios.google_sheets.GoogleSheetsBalanceAndLedger ''
      params:
        sheetStructure:
            # This Google Sheet is an example that should work out of the box
            sheet: 1U2SAvRuwcA74heo2dAeFvKuH5zFLowlCGdn4-tcVC9U

is any line more to edit?

**Comment by avibrazil** [comment]
You´ll have trouble using the Google Sheets driver.
Publish each sheet as CSV and then use the `URIBalanceOrLedger` driver.
Wait, I see the YAML example for this is not updated on the repo, let me update it and provide the link.

**Comment by avibrazil** [comment]
[This new example](https://github.com/avibrazil/investorzilla/blob/main/config_examples/investorzilla.yaml) should get you going with fake data on a Google Sheets.
Just put it on an empty folder and run `investorzilla` from inside that folder.

**Comment by johnfelipe** [comment]
can u send me a video pls, because i cant test your app, look my all process in this video:

https://drive.google.com/file/d/1agnEevOS2_AbMvDpShYyJEi01o2DGYQb/view?usp=sharing

help me asap

**Comment by avibrazil** [comment]
Here is a video of an installation from scratch and boot with example configuration.

https://www.youtube.com/watch?v=CrR-PoXhPQY

I also published this video on the project README.

You are helping me find documentation details that needed fix. Thank you for that.

**Comment by johnfelipe** [comment]
witch version of python, i have ubuntu 22 with python 3.10 using env or can run in ubuntu 20 with python 3.8, i do this steps:

	git clone https://github.com/avibrazil/investorzilla
	cd investorzilla/

	python3 -m venv env
	source env/bin/activate

	pip3 install investorzilla
	cd investorzilla/
	mkdir myportfolio
	cp /root/investorzilla/config_examples/investorzilla.yaml /root/investorzilla/myportfolio/investorzilla.yaml
	cd myportfolio

	investorzilla

in ubuntu 22 with python 3.10

and still not works this is console log:

https://gist.github.com/johnfelipe/77d402930f01b9898320feff7db655e2

may be do it in notroot user?

**Comment by johnfelipe** [comment]
no in an notroot user not works

	felipe@template:~/investorzilla/myportfolio$ pip install investorzilla --user
	Requirement already satisfied: investorzilla in /home/felipe/.local/lib/python3.10/site-packages (2.4.1)
	Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.10/dist-packages (from investorzilla) (2.1.4)
	Requirement already satisfied: pyaml in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (23.9.7)
	Requirement already satisfied: sqlalchemy in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (2.0.23)
	Requirement already satisfied: streamlit in /usr/local/lib/python3.10/dist-packages (from investorzilla) (1.29.0)
	Requirement already satisfied: google-auth-oauthlib in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (1.1.0)
	Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from investorzilla) (2020.6.20)
	Requirement already satisfied: pandas-datareader in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (0.10.0)
	Requirement already satisfied: matplotlib in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (3.8.2)
	Requirement already satisfied: google-auth-httplib2 in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (0.1.1)
	Requirement already satisfied: google-api-python-client in /home/felipe/.local/lib/python3.10/site-packages (from investorzilla) (2.110.0)
	Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=2->investorzilla) (2022.1)
	Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2->investorzilla) (2023.3)
	Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=2->investorzilla) (1.26.2)
	Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=2->investorzilla) (2.8.2)
	Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /home/felipe/.local/lib/python3.10/site-packages (from google-api-python-client->investorzilla) (2.15.0)
	Requirement already satisfied: httplib2<1.dev0,>=0.15.0 in /usr/lib/python3/dist-packages (from google-api-python-client->investorzilla) (0.20.2)
	Requirement already satisfied: uritemplate<5,>=3.0.1 in /home/felipe/.local/lib/python3.10/site-packages (from google-api-python-client->investorzilla) (4.1.1)
	Requirement already satisfied: google-auth<3.0.0.dev0,>=1.19.0 in /home/felipe/.local/lib/python3.10/site-packages (from google-api-python-client->investorzilla) (2.25.2)
	Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/felipe/.local/lib/python3.10/site-packages (from google-auth-oauthlib->investorzilla) (1.3.1)
	Requirement already satisfied: cycler>=0.10 in /home/felipe/.local/lib/python3.10/site-packages (from matplotlib->investorzilla) (0.12.1)
	Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.10/dist-packages (from matplotlib->investorzilla) (10.1.0)
	Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->investorzilla) (23.2)
	Requirement already satisfied: kiwisolver>=1.3.1 in /home/felipe/.local/lib/python3.10/site-packages (from matplotlib->investorzilla) (1.4.5)
	Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib->investorzilla) (2.4.7)
	Requirement already satisfied: contourpy>=1.0.1 in /home/felipe/.local/lib/python3.10/site-packages (from matplotlib->investorzilla) (1.2.0)
	Requirement already satisfied: fonttools>=4.22.0 in /home/felipe/.local/lib/python3.10/site-packages (from matplotlib->investorzilla) (4.46.0)
	Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pandas-datareader->investorzilla) (2.31.0)
	Requirement already satisfied: lxml in /home/felipe/.local/lib/python3.10/site-packages (from pandas-datareader->investorzilla) (4.9.3)
	Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyaml->investorzilla) (5.4.1)
	Requirement already satisfied: greenlet!=0.4.17 in /home/felipe/.local/lib/python3.10/site-packages (from sqlalchemy->investorzilla) (3.0.2)
	Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->investorzilla) (4.9.0)
	Requirement already satisfied: click<9,>=7.0 in /usr/lib/python3/dist-packages (from streamlit->investorzilla) (8.0.3)
	Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (4.25.1)
	Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (6.4)
	Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (0.10.2)
	Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit->investorzilla) (1.4)
	Requirement already satisfied: validators<1,>=0.2 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (0.22.0)
	Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (5.3.2)
	Requirement already satisfied: tzlocal<6,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (5.2)
	Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (8.2.3)
	Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (3.1.40)
	Requirement already satisfied: watchdog>=2.1.5 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (3.0.0)
	Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (13.7.0)
	Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (0.8.1b0)
	Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (5.2.0)
	Requirement already satisfied: importlib-metadata<7,>=1.4 in /usr/lib/python3/dist-packages (from streamlit->investorzilla) (4.6.4)
	Requirement already satisfied: pyarrow>=6.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->investorzilla) (14.0.1)
	Requirement already satisfied: jsonschema>=3.0 in /usr/lib/python3/dist-packages (from altair<6,>=4.0->streamlit->investorzilla) (3.2.0)
	Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit->investorzilla) (0.12.0)
	Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit->investorzilla) (3.0.0)
	Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->investorzilla) (4.0.11)
	Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/felipe/.local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->investorzilla) (1.62.0)
	Requirement already satisfied: rsa<5,>=3.1.4 in /home/felipe/.local/lib/python3.10/site-packages (from google-auth<3.0.0.dev0,>=1.19.0->google-api-python-client->investorzilla) (4.9)
	Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3.0.0.dev0,>=1.19.0->google-api-python-client->investorzilla) (0.2.1)
	Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=2->investorzilla) (1.16.0)
	Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader->investorzilla) (3.3.2)
	Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pandas-datareader->investorzilla) (3.3)
	Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pandas-datareader->investorzilla) (1.26.5)
	Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->investorzilla) (3.2.0)
	Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit->investorzilla) (3.0.0)
	Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit->investorzilla) (2.17.2)
	Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->investorzilla) (5.0.1)
	Requirement already satisfied: MarkupSafe>=2.0.0rc2 in /usr/lib/python3/dist-packages (from jinja2->altair<6,>=4.0->streamlit->investorzilla) (2.0.1)
	Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit->investorzilla) (0.1.2)
	Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa<5,>=3.1.4->google-auth<3.0.0.dev0,>=1.19.0->google-api-python-client->investorzilla) (0.4.8)
	felipe@template:~/investorzilla/myportfolio$ investorzilla
	investorzilla: command not found

i will do it in ubuntu 20 with python 3.8...

**Comment by johnfelipe** [comment]
doing in root user in ubuntu 20 with python 3.8 show me this logs:

https://gist.github.com/johnfelipe/05a02e80225cee5f89a4b943a49fd7a5

![SNAG-0013](https://github.com/avibrazil/investorzilla/assets/428820/2e7f4152-ccb9-487e-8041-92f27bc1dc2e)

i think need to help me to solve that issues in `pip3 install investorzilla --user`

and using env in notroot user show this:

	(env) felipe@felipe:~/tmp/myportfolio$ ls
	env  investorzilla.yaml
	(env) felipe@felipe:~/tmp/myportfolio$ investorzilla
	Traceback (most recent call last):
	  File "/home/felipe/tmp/myportfolio/env/bin/investorzilla", line 5, in <module>
		from investorzilla.__main__ import main
	  File "/home/felipe/tmp/myportfolio/env/lib/python3.8/site-packages/investorzilla/__main__.py", line 49, in <module>
		main()
	  File "/home/felipe/tmp/myportfolio/env/lib/python3.8/site-packages/investorzilla/__main__.py", line 20, in main
		str(importlib.resources.files(investorzilla) / 'streamlit_ui.py'),
	AttributeError: module 'importlib.resources' has no attribute 'files'

**Comment by avibrazil** [comment]
That’s because Python 3.8 is too old and doesn’t have this feature. I’m fixing dependencies to require Python 3.9 minimum.
